-- 检查数据库表结构
USE `ihc`;

-- 检查 artworks 表字段
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ihc' AND TABLE_NAME = 'artworks'
ORDER BY ORDINAL_POSITION;

-- 检查 products 表字段
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ihc' AND TABLE_NAME = 'products'
ORDER BY ORDINAL_POSITION;

-- 检查新表是否存在
SHOW TABLES LIKE 'comments';
SHOW TABLES LIKE 'product_likes';
SHOW TABLES LIKE 'views';

